### PR TITLE
#160195709 Login.html file added

### PR DESCRIPTION
**Pull request by TeamoreA**
**What does this PR do?**

- Allows a user to login

**Description of Task to be completed?**

- add login.html page.

**How it can be manually tested?**

- clone the project https://github.com/TeamoreA/Fast-Food-Fast/ and run the specified file

**What are the relevant pivotal tracker stories?**
[##160195709](https://www.pivotaltracker.com/n/projects/2194758)
screenshot 56

### CODE REVIEW

**Comment by danuluma** [comment]
check typo .....should end with .html

**Comment by mdn-network** [comment]
[put your styles in an external css](https://www.w3schools.com/html/html_css.asp) and  also check on [PR naming](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Comment by PromasterGuru** [comment]
Try to format your PR as follows:
**What does this PR do?**
....
....
.....

**Description of Task to be completed?**
....
....
....

**How should this be manually tested?**
....
....
....

**What are the relevant pivotal tracker stories?**
[pivotal tracker id](url to your pivotal tracker it.)
....NB: You should not remove the braces and brackets i.g. []()

**Screenshots (if applicable)**
....drag your screenshot and paste it here

**Comment by emulati90** [comment]
Awesome bro

**Pull request closed without merging**
