### PR TITLE
160198473 Landing page added

### PR DESCRIPTION
**Pull request by TeamoreA**
**What does this PR do?**

- Add a welcome page

**Description of Task to be completed?**

- add index.html
**How it can be manually tested?**

- clone the project https://github.com/TeamoreA/Fast-Food-Fast/ and run the specified file

**What are the relevant pivotal tracker stories?**
[#160198473](https://www.pivotaltracker.com/n/projects/2194758)
screenshot 64

### CODE REVIEW

**Comment by PromasterGuru** [comment]
Awesome :+1: Try to add screenshots

**Comment by kamaudan** [comment]
Good work, adjust the opacity a little bit.

**Comment by TeamoreA** [comment]
To more or less opaque?

**Comment by EmmanuelBeja** [comment]
less would do for me

**Comment by kamaudan** [comment]
I think less, or it covers all the page for uniformity.

**Comment by ItsCosmas** [comment]
Nice UI

**Comment by ItsCosmas** [comment]
Hii ndio landing page
https://teamorea.github.io/Fast-Food-Fast/
But If I click on the Home Link from other links,say niko kwa register inanipeleka kwa hii link
https://teamorea.github.io/Fast-Food-Fast/user/order_food.html

**Pull request merged**
